hw06 - cover logic with tests
romakorinenko/hw-test pull request #6
Opened 2024-08-26 18:42 UTC by romakorinenko

## Домашнее задание №6 «Покрыть тестами предыдущие задания»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-08-26 21:38 UTC, vladislavmass requested changes

2024-08-26 21:38 UTC, vladislavmass commented on hw06_testing/chessboard/chessboard_test.go
> +func TestChessboard(t *testing.T) {
Данный тест работает не проверяет корректную работу программы. Например если я просто напишу программу , которая в строку запишет в начале нужное число черных клеток, а потом белых то этот код пройдет этот тест хотя задачу и не решает. Мы должны проверять то, что на выходе у нас действительно шахматная доска

2024-08-26 21:38 UTC, vladislavmass commented on hw06_testing/fixapp/staff_returner_test.go
> +func TestGetStaffFromFile(t *testing.T) {
Тестировать нужно функции, которые уже были в коде. Тут же для тестов создана некая синтетическая функция и идет попытка ее протестировать. Данный тест принять не могу

2024-08-27 16:49 UTC, romakorinenko commented on hw06_testing/chessboard/chessboard_test.go
> +func TestChessboard(t *testing.T) {
переписал тест, теперь проверяется шахматная доска, а не количество ячеек по цветам

2024-08-27 16:54 UTC, romakorinenko commented on hw06_testing/fixapp/staff_returner_test.go
> +func TestGetStaffFromFile(t *testing.T) {
попробовал переписать тест, теперь больше похоже на первоначальный вариант функций

2024-08-27 19:38 UTC, vladislavmass approved these changes

2024-08-28 07:33 UTC, merged